version: '2'
services:

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - minio-data:/bitnami/minio/data
    networks:
      - modo-network

  htsget:
    image: ghcr.io/umccr/htsget-rs:dev-latest
    networks:
      - modo-network
    volumes:
      - minio-data:/data/s3

  modo-server:
    build: ./modo-server
    ports:
      - '8000:8000'
      - '9000:9000'
    networks:
      - modo-network
    volumes:
      - minio-data:/data/s3
    command: uvicorn --host 0.0.0.0 --port 8000 --reload server:app

volumes:
  minio-data:
    driver: local

networks:
  modo-network:
