# An example for a server which uses s3 storage with data located in "bucket".
# Run with `cargo run -p htsget-actix --features s3-storage -- --config htsget-config/examples/config-files/s3_storage.toml`

id = "modos-htsget"
ticket_server_cors_allow_headers = "All"
ticket_server_cors_allow_methods = "All"
ticket_server_cors_allow_credentials = true
ticket_server_cors_max_age = 300

data_server_enabled = false

[[resolvers]]
regex = ".*"
substitution_string = "$0"

[resolvers.storage]
endpoint = 'http://172.23.0.2:9000' # template
path_style = true # template
bucket = 'modos-demo' # template
